/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateYuyuArgs } from "./CreateYuyuArgs";
import { UpdateYuyuArgs } from "./UpdateYuyuArgs";
import { DeleteYuyuArgs } from "./DeleteYuyuArgs";
import { YuyuFindManyArgs } from "./YuyuFindManyArgs";
import { YuyuFindUniqueArgs } from "./YuyuFindUniqueArgs";
import { Yuyu } from "./Yuyu";
import { YuyuService } from "../yuyu.service";

@graphql.Resolver(() => Yuyu)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class YuyuResolverBase {
  constructor(
    protected readonly service: YuyuService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Yuyu",
    action: "read",
    possession: "any",
  })
  async _yuyusMeta(
    @graphql.Args() args: YuyuFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Yuyu])
  @nestAccessControl.UseRoles({
    resource: "Yuyu",
    action: "read",
    possession: "any",
  })
  async yuyus(@graphql.Args() args: YuyuFindManyArgs): Promise<Yuyu[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Yuyu, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Yuyu",
    action: "read",
    possession: "own",
  })
  async yuyu(@graphql.Args() args: YuyuFindUniqueArgs): Promise<Yuyu | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Yuyu)
  @nestAccessControl.UseRoles({
    resource: "Yuyu",
    action: "create",
    possession: "any",
  })
  async createYuyu(@graphql.Args() args: CreateYuyuArgs): Promise<Yuyu> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Yuyu)
  @nestAccessControl.UseRoles({
    resource: "Yuyu",
    action: "update",
    possession: "any",
  })
  async updateYuyu(@graphql.Args() args: UpdateYuyuArgs): Promise<Yuyu | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Yuyu)
  @nestAccessControl.UseRoles({
    resource: "Yuyu",
    action: "delete",
    possession: "any",
  })
  async deleteYuyu(@graphql.Args() args: DeleteYuyuArgs): Promise<Yuyu | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
