/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateTsetArgs } from "./CreateTsetArgs";
import { UpdateTsetArgs } from "./UpdateTsetArgs";
import { DeleteTsetArgs } from "./DeleteTsetArgs";
import { TsetFindManyArgs } from "./TsetFindManyArgs";
import { TsetFindUniqueArgs } from "./TsetFindUniqueArgs";
import { Tset } from "./Tset";
import { User } from "../../user/base/User";
import { TsetService } from "../tset.service";
@graphql.Resolver(() => Tset)
export class TsetResolverBase {
  constructor(protected readonly service: TsetService) {}

  async _tsetsMeta(
    @graphql.Args() args: TsetFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Tset])
  async tsets(@graphql.Args() args: TsetFindManyArgs): Promise<Tset[]> {
    return this.service.findMany(args);
  }

  @graphql.Query(() => Tset, { nullable: true })
  async tset(@graphql.Args() args: TsetFindUniqueArgs): Promise<Tset | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Tset)
  async createTset(@graphql.Args() args: CreateTsetArgs): Promise<Tset> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        test: args.data.test
          ? {
              connect: args.data.test,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Tset)
  async updateTset(@graphql.Args() args: UpdateTsetArgs): Promise<Tset | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          test: args.data.test
            ? {
                connect: args.data.test,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Tset)
  async deleteTset(@graphql.Args() args: DeleteTsetArgs): Promise<Tset | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, { nullable: true })
  async test(@graphql.Parent() parent: Tset): Promise<User | null> {
    const result = await this.service.getTest(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
